### ISSUE TITLE
Populate as the inverse of Apply

### ISSUE THREAD

**Issue by jwiegley** [patrickt/fastsum#25]
The following typeclass makes it possible to "populate" a sum by attempting a series of operations in `MonadPlus`, for example parsers:
```haskell
class Producible m f where
  produce :: m (f v)

class Populate m (fs :: [* -> *]) where
  populate :: m (Sum fs b)

instance (Producible m t, MonadPlus m) => Populate m '[t] where
  populate = fmap inject (produce @m @t)

instance
  {-# OVERLAPPING #-}
  (Populate m (u ': r), Producible m t, MonadPlus m) =>
  Populate m (t ': u ': r)
  where
  populate =
    fmap inject (produce @m @t)
      <|> fmap weaken (populate @m @(u ': r))
```
This could be implemented for a Megaparsec type as follows:
```haskell
instance Producible Parser (Const Entry) where
  produce = fmap Const parseEntry
```
Now you can populate a `Sum '[Const a, Const b, Const c] v` as long as there are parsers that can produce values of type `a`, `b` and `c`.

**Comment by patrickt** [comment]
Wow, @jwiegley, I really like this (though can you just get by with Alternative rather than MonadPlus?). I'd happily accept a patch for this. _EDIT: I wanted to take it for a spin myself, so I've pushed up a branch containing this. Also, I was right in that this can get by with just Alternative._

Also, thanks so much for filing all these issues! I'm so sorry I dropped the ball 🙈

**Comment by jwiegley** [comment]
I'm well known for letting PRs and issues languish for months without reply, so you'll get no remonstrations from me. :) Thank you for hearing me in the end!

**Comment by robrix** [comment]
Just wanted to note that this is _really_ slick.
